[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'jeetsukumaran/vim-nefertiti'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo   = 'Shougo/unite.vim'


[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

# settings of status bar
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugin]]
repo = 'vim-airline/vim-airline-themes'

[[plugin]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'tpope/vim-fugitive'

# setting of lsp
[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
