[[plugins]]
repo = 'wakatime/vim-wakatime'

[[plugins]]
repo = 'jeetsukumaran/vim-nefertiti'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

# Unite.vimで最近使ったファイルを表示できるようにする
[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

# settings of status bar
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# setting of lsp
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = 'call coil398#init#coc#hook_source()'

# japanese help
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# show whitespaces
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'


# setting of colorscheme
[[plugins]]
repo = 'joshdick/onedark.vim'

# plugin for template
[[plugins]]
repo = 'mattn/vim-sonictemplate'


[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'thinca/vim-quickrun'
