[[plugins]]
repo='Shougo/ddc.vim'
on_event = ['InsertEnter', 'CmdlineEnter']
depends='denops.vim'
hooks_file="$BASE_DIR/rc/hooks/ddc.lua"

[[plugins]]
repo="Shougo/pum.vim"
on_source='ddc.vim'

[[plugins]]
repo="zbirenbaum/copilot.lua"
on_event="InsertEnter"
hooks_file="$BASE_DIR/rc/hooks/copilot.lua"

[[plugins]]
repo="Shougo/ddc-nvim-lsp"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-around"
on_source="ddc.vim"

[[plugins]]
repo="LumaKernel/ddc-file"
on_source="ddc.vim"

[[plugins]]
repo="matsui54/ddc-buffer"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-source-cmdline"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-source-mocword"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-source-cmdline-history"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-source-lsp"
on_source="ddc.vim"

[[plugins]]
repo="uga-rosa/ddc-source-nvim-lua"
on_source="ddc.vim"

[[plugins]]
repo="LumaKernel/ddc-source-file"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-sorter_rank"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-ui-pum"
depends = 'pum.vim'
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-ui-native"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-converter_remove_overlap"
on_source="ddc.vim"

[[plugins]]
repo="tani/ddc-fuzzy"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-matcher_head"
on_source="ddc.vim"

[[plugins]]
repo="tani/ddc-path"
on_source="ddc.vim"

[[plugins]]
repo="uga-rosa/ddc-source-lsp-setup"
on_source="ddc.vim"

[[plugins]]
repo="Shougo/ddc-filter-converter_truncate_abbr"
on_source="ddc.vim"

[[plugins]]
repo="lambdalisue/guise.vim"
on_source="ddc.vim"

[[plugins]]
repo="uga-rosa/ddc-previewer-floating"
on_source="ddc.vim"

[[plugins]]
repo="vim-skk/skkeleton"
on_source='ddc.vim'
hooks_file="$BASE_DIR/rc/hooks/skk.lua"

[[plugins]]
repo="skk-dev/dict"
on_source="skkeleton"

[[plugins]]
repo = "uga-rosa/denippet.vim"
on_source = "ddc.vim"
hooks_file="$BASE_DIR/rc/hooks/denippet.lua"

[[plugins]]
repo="delphinus/skkeleton_indicator.nvim"
on_source="ddc.vim"
lua_source="""
require("skkeleton_indicator").setup()
"""
