[[plugins]]
repo = 'toppair/peek.nvim'
build='deno task --quiet build:fast'
on_ft="md"
lua_source='''
require("peek").setup({
    auto_load = true,        -- whether to automatically load preview when
    -- entering another markdown buffer
    close_on_bdelete = true, -- close preview window on buffer delete
    syntax = true,           -- enable syntax highlighting, affects performance
    theme = 'dark',          -- 'dark' or 'light'
    update_on_change = true,
    app = 'browser', -- 'webview', 'browser', string or a table of strings
    -- explained below
    filetype = { 'markdown' }, -- list of filetypes to recognize as markdown
    -- relevant if update_on_change is true
    throttle_at = 200000,   -- start throttling when file exceeds this
    -- amount of bytes in size
    throttle_time = 'auto', -- minimum amount of time in milliseconds
    -- that has to pass before starting new render
  })
vim.api.nvim_create_user_command('PeekOpen', require('peek').open, {})
vim.api.nvim_create_user_command('PeekClose', require('peek').close, {})
vim.api.nvim_create_user_command('Peek', function() if require("peek").is_open() then require("peek").close() else require("peek").open() end end, {})
'''

[[plugins]]
on_ft="md"
repo = 'mzlogin/vim-markdown-toc'

[[plugins]]
repo="Decodetalkers/csv-tools.lua"
on_ft = "csv"
lua_source='''
local status, csvtools = pcall(require, "csvtools")
if not status then
	return
end

csvtools.setup({
	before = 10,
	after = 10,
	clearafter = true,
	-- this will clear the highlight of buf after move
	showoverflow = false,
	-- this will provide a overflow show
	titelflow = true,
	-- add an alone title
})
'''

[[plugins]]
repo = 'thinca/vim-partedit'
on_cmd = 'Partedit'
on_func = 'partedit#start'
hook_add = '''
    let g:partedit#prefix_pattern = '\s*'
    let g:partedit#auto_prefix = 0
'''

[ftplugin]
toml_markdown = '''
 setl foldmethod=expr
 setl foldexpr=<SID>fold_expr(v:lnum)

 function! s:fold_expr(lnum) abort
   let line = getline(a:lnum)
   return line ==# '' || line[0:3] ==# '    '
 endfunction
 nnoremap <buffer> <C-p> <Cmd>call <SID>operator_partedit()<CR>
 function! s:operator_partedit() abort
  let context = context_filetype#get()
  if context.range == [[0, 0], [0, 0]]
    echohl WarningMsg
    echomsg 'Context is not found'
    echohl NONE
    return
  endif
  call partedit#start(context.range[0][0], context.range[1][0],
 	   \ {'filetype': context.filetype})
  nnoremap <buffer><nowait> Q <Cmd>w<CR><Cmd>ParteditEnd<CR>
 endfunction
'''
