[[plugins]]
repo = "neovim/nvim-lspconfig"
on_event = ['BufNewFile', 'BufRead']
on_source = ["ddc.vim", "ddu.vim"]
hooks_file="$BASE_DIR/rc/hooks/lsp.lua"

[[plugins]]
repo = "nvimtools/none-ls.nvim"
on_event = ['BufNewFile', 'BufRead']
hooks_file="$BASE_DIR/rc/hooks/none_ls.lua"

