[[plugins]]
repo = "neovim/nvim-lspconfig"
on_cmd = "LspInfo"
on_source = ["mason.nvim", "ddc.vim"]

[[plugins]]
repo = "williamboman/mason-lspconfig.nvim"
on_cmd = ['LspInstall', 'LspUninstall']
on_source = "mason.nvim"

[[plugins]]
repo = "williamboman/mason.nvim"
on_event = ['BufNewFile', 'BufRead']
depends = ['mason-lspconfig.nvim', 'nvim-lspconfig']
hooks_file='$BASE_DIR/rc/hooks/lsp.lua'

[[plugins]]
repo = "nvimtools/none-ls.nvim"
on_event = ['BufNewFile', 'BufRead']
depends=['mason.nvim', 'plenary.nvim']
hooks_file="$BASE_DIR/rc/hooks/none_ls.lua"

[[plugins]]
repo = "ryoppippi/lsp_lines.nvim"
on_event = ['BufNewFile', 'BufRead']
lua_source = """
vim.keymap.set({"n", "v"}, "<leader>l", "<cmd>lua require('lsp_lines').toggle()<CR>")
require("lsp_lines").setup()
"""
