[[plugins]]
repo = "neovim/nvim-lspconfig"
on_cmd = "LspInfo"
on_source = ["mason.nvim", "ddc.vim", "ddu.vim"]

[[plugins]]
repo = "williamboman/mason-lspconfig.nvim"
on_cmd = ['LspInstall', 'LspUninstall']
on_source = "mason.nvim"

[[plugins]]
repo = "williamboman/mason.nvim"
on_event = ['BufNewFile', 'BufRead']
hooks_file='$BASE_DIR/rc/hooks/lsp.lua'

[[plugins]]
repo = "nvimtools/none-ls.nvim"
on_event = ['BufNewFile', 'BufRead']
hooks_file="$BASE_DIR/rc/hooks/none_ls.lua"

