[[pluging]]
repo = "norcalli/nvim-colorizer.lua"
lua_add='''
vim.opt.termguicolors = true
require("colorizer").setup({
	"*",
})
'''
[[plugins]]
repo = "ellisonleao/gruvbox.nvim"
hook_add='''
set background=dark
colorscheme gruvbox
'''
# dot repeat
[[plugins]]
repo="tpope/vim-repeat"

# utility
[[plugins]]
repo="nvim-lua/plenary.nvim"
on_source=['none-ls.nvim']

[[plugins]]
repo="nvim-lualine/lualine.nvim"
hooks_file="$BASE_DIR/rc/hooks/lualine.lua"
# keep lastest cursor position
[[plugins]]
repo="ethanholz/nvim-lastplace"
lua_source='''
require("nvim-lastplace").setup()
'''
