[[plugins]]
repo="cocopon/iceberg.vim"
hook_add='''
colorscheme iceberg
'''

# dot repeat
[[plugins]]
repo="tpope/vim-repeat"

# utility
[[plugins]]
repo="nvim-lua/plenary.nvim"
on_source=['none-ls.nvim']

[[plugins]]
repo="nvim-lualine/lualine.nvim"
hooks_file="$BASE_DIR/rc/hooks/lualine.lua"

[[plugins]]
repo="ethanholz/nvim-lastplace"
lua_source='''
require("nvim-lastplace").setup()
'''

# [[plugins]]
# repo="Shougo/deol.nvim"
# hooks_file='$BASE_DIR/rc/hooks/deol.lua'

# [[plugins]]
# repo = 'tani/dmacro.nvim'
# lua_add='''
# vim.keymap.set({ "i", "n" }, '<C-t>', '<Plug>(dmacro-play-macro)<CR>')
# '''
