[[pluging]]
repo = "norcalli/nvim-colorizer.lua"
lua_add='''
vim.opt.termguicolors = true
require("colorizer").setup({
	"*",
})
'''
# auto comment out
[[plugins]]
repo="luochen1990/rainbow"
lua_add='''
vim.g.rainbow_active = 1
'''
# dot repeat
[[plugins]]
repo="tpope/vim-repeat"
# utility
[[plugins]]
repo="nvim-lua/plenary.nvim"

# keep lastest cursor position
[[plugins]]
repo="ethanholz/nvim-lastplace"
on_event = ['BufRead']
lua_source='''
require("nvim-lastplace").setup()
'''

[[plugins]]
repo='uga-rosa/ugaterm.nvim'
lua_add='''
vim.keymap.set({ "n", "t" }, "<C-t>", "<cmd>UgatermOpen -toggle<cr>", { noremap = true, silent = true })
'''

[[plugins]]
repo="windwp/nvim-autopairs"
on_event = ['InsertEnter']
lua_source='''
require("nvim-autopairs").setup({
disable_filetype = { "TelescopePrompt", "vim" },
})
'''

[[plugins]]
repo="lukas-reineke/indent-blankline.nvim"
on_event = ['BufNewFile', 'BufRead']
lua_source='''
require('ibl').setup({})
'''

[[plugins]]
repo="nvim-lualine/lualine.nvim"
on_event = ['BufNewFile', 'BufRead']
hooks_file="$BASE_DIR/rc/hooks/lualine.lua"

# auto pair and tag close
[[plugins]]
repo="windwp/nvim-ts-autotag"
on_event = ['InsertEnter']
# surround
[[plugins]]
repo="kylechui/nvim-surround"
on_event = ['InsertEnter']
lua_source='''
require("nvim-surround").setup()
'''

[[plugins]]
repo="mattn/vim-sonictemplate"
on_cmd='Template'
lua_source='''
vim.g.sonictemplate_key = 0
vim.g.sonictemplate_intelligent_key = 0
vim.g.sonictemplate_postfix_key = 0
vim.g.sonictemplate_vim_template_dir = "~/.dotfiles/.config/nvim/template"
'''

[[plugins]]
repo='skanehira/denops-silicon.vim'
on_cmd='Silicon'

[[plugins]]
repo="numToStr/Comment.nvim"
on_event = ['BufNewFile', 'BufRead']
lua_source='''
require("Comment").setup({
 ---LHS of toggle mappings in NORMAL mode
 ---@type table
 toggler = {
 	---Line-comment toggle keymap
 	line = "col",
 	---Block-comment toggle keymap
 	block = "cob",
	},
})
'''

[[plugins]]
repo="nvim-treesitter/nvim-treesitter"
on_event = ['BufNewFile', 'BufRead']
hooks_file="$BASE_DIR/rc/hooks/treesitter.lua"

[[plugins]]
repo="folke/todo-comments.nvim"
on_event = ['BufNewFile', 'BufRead']
lua_source='''
require("todo-comments").setup({})
vim.keymap.set("n", "<Leader>tq", "<cmd>TodoQuickFix<cr>", { noremap = true, silent = true })
'''


[[plugins]]
repo="kana/vim-smartword"
on_event = ['BufNewFile', 'BufRead']
lua_source='''
vim.keymap.set("n", "w", "<Plug>(smartword-w)")
vim.keymap.set("n", "b", "<Plug>(smartword-b)")
vim.keymap.set("n", "e", "<Plug>(smartword-e)")
'''

[[plugins]]
repo="lewis6991/gitsigns.nvim"
on_event = ['BufNewFile', 'BufRead']
lua_source='''
require('gitsigns').setup()
'''

[[plugins]]
repo='lambdalisue/gin.vim'
on_event = ['BufNewFile', 'BufRead']
hooks_file="$BASE_DIR/rc/hooks/gin.lua"

# show diff from recover file
[[plugins]]
on_event=['SwapExists']
repo="chrisbra/Recover.vim"

[[plugins]]
repo='phaazon/hop.nvim'
on_event = ['BufNewFile', 'BufRead']
hooks_file="$BASE_DIR/rc/hooks/hop.lua"

[[plugins]]
repo="dstein64/vim-startuptime"
