[[plugins]]
repo="windwp/nvim-autopairs"
# on_lua='''
# local status, autopairs = pcall(require, "nvim-autopairs")
# if not status then
# 	return
# end
# autopairs.setup({
# disable_filetype = { "TelescopePrompt", "vim" },
# })
# '''
