[[pluging]]
repo = "norcalli/nvim-colorizer.lua"
lua_add='''
vim.opt.termguicolors = true
require("colorizer").setup({
	"*",
})
'''
# auto comment out
[[plugins]]
repo="luochen1990/rainbow"
lua_add='''
vim.g.rainbow_active = 1
'''
# dot repeat
[[plugins]]
repo="tpope/vim-repeat"
# utility
[[plugins]]
repo="nvim-lua/plenary.nvim"

[[plugins]]
repo="nvim-lua/popup.nvim"

# buffer sizer
[[plugins]]
repo="simeji/winresizer"

# show diff from recover file
[[plugins]]
repo="chrisbra/Recover.vim"

# keep lastest cursor position
[[plugins]]
repo="ethanholz/nvim-lastplace"
lua_add='''
require("nvim-lastplace").setup()
'''

[[plugins]]
repo="kyazdani42/nvim-web-devicons"
lua_add='''
local status, icons = pcall(require, "nvim-web-devicons")
if not status then
	return
end

icons.setup({
	-- your personnal icons can go here (to override)
	-- DevIcon will be appended to `name`
	override = {},
	-- globally enable default icons (default to false)
	-- will get overriden by `get_icons` option
	default = true,
})
'''
